# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: "3.7"

services:
  authentication-service:
    image: authentication-service
    container_name: authentication-service
    build:
      context: ./authentication-service-core
      args:
        jarFile: "build/libs/authentication-service-core-1.0.jar"
    depends_on:
      - sms-gate
    environment:
      SMS_GATE_URL: "http://sms-gate:8080"
    ports:
      - "8080:8080"
    restart: always

  sms-gate:
    image: sms-gate
    container_name: sms-gate
    build:
      context: ./authentication-service-sms-gate
      args:
        jarFile: "build/libs/authentication-service-sms-gate-1.0.jar"
    environment:
      TWILIO_AUTH_SID: "1"
      TWILIO_AUTH_TOKEN: "1"
      TWILIO_FROM: "1"
    ports:
      - "8081:8080"
    restart: always
